### ISSUE TITLE
Knowledge Base Organization

### ISSUE THREAD

**Issue by mikhael28** [fsapprenticeship/fsa-hub#10]
Deb, we want to make sure the knowledge base is organized well so that we can effectively use the Content Studio to add resources as we see fit, and so that we can query multiple types of schema objects effectively. Right now, there are two top level views - Knowledge Base and Seattle. We want to add a third, AWS, that has resources devoted to S3, Lambda, EC2, RDS, etc. For that, we will want to create new schema objects for all those tools (S3, etc.)

As a way of getting onboarded, would you go ahead and modify the schema.js, add new schemaTypes, and update the 'work table' I believe its called, which is responsible for rendering the Content Studio in a way that's easy for us to add new things. If you have any other ideas for how to effectively organize and categorize the content, let me know!

**Comment by mikhaelbendavid** [comment]
In the future, we will want people to be able to create their own custom schemas, especially when it comes to the tech resources in their city of choice. Seattle resources are great for Seattle, not much help to Portland.

**Comment by mikhaelbendavid** [comment]
Updated the schema for a big chunk of the knowledge base, need to pay more attention to AWS and add some subcategory schemas there.

**Comment by mikhaelbendavid** [comment]
Moving forward, we need to put together a way for people to put forth suggestions for resources, and have a way for admin to review them without necessarily giving access to the Sanity Studio.

**Comment by mikhael28** [comment]
Closing, creating a separate ticket for adding the contentRank attribute to each piece of content.
