### ISSUE TITLE
CreateProfileScreen issues

### ISSUE THREAD

**Issue by pcoutin** [fsapprenticeship/fsa-hub#116]
**Describe the bug**

- Everything is always undefined when editing the profile
- Clicking on "Edit Name" after changing things takes me back to the "My Profile", then going on "Edit Profile" again, everything is undefined again
- Can't scroll down to see the Github username field when editing the profile, when inputting on it

**To Reproduce**
1. Log in
2. Go on "Create Profile"

**Screenshots**
not yet

**Desktop (please complete the following information):**
 - OS: Android 9
 - Expo, React Native interface

**Smartphone (please complete the following information):**
 - Device: LG Q7+

**Comment by mikhael28** [comment]
@pcoutin I believe this has been addressed in the some of the latest merges, I'm going to close this!
