### ISSUE TITLE
Mark completed buttons not working after profile creation

### ISSUE THREAD

**Issue by Vegitarius** [fsapprenticeship/fsa-hub#128]
After I created my account I went to the experience tab and attempted to click through and mark the achievements I had already completed but I could not, After refreshing and coming back later again returning to the experience tab the button then read Mark Completed and I was able to complete the achievements

**Expected behavior**
For the Mark Completed buttons to appear after profile creations without refreshing application.

**Smartphone (please complete the following information):**
 - LG V40 Thinq
 - Android Version 8.1.0
- Expo App

**Comment by mikhael28** [comment]
This has been addressed in the latest round of commits @Vegitarius !
