### ISSUE TITLE
Query Top Level Sanity Buckets

### ISSUE THREAD

**Issue by mikhaelbendavid** [fsapprenticeship/fsa-hub#13]
This would be a React view with the Sanity API providing the data.

**Comment by mikhaelbendavid** [comment]
Would be great to starting implement Material UI in preparation for Topher's UI, but maybe keep the React-Bootstrap implementation of the Grid system.

**Comment by thegreatsantini** [comment]
I'll add material UI.

**Comment by mikhaelbendavid** [comment]
Like a boss @thegreatsantini
