### ISSUE TITLE
PaperTextfield.js should be a simple wrapper

### ISSUE THREAD

**Issue by iareintelligent** [fsapprenticeship/fsa-hub#22]
Redux just made all these components a lot more reusable; need to refactor and separate concerns (assigning this one to myself).

**Comment by mikhaelbendavid** [comment]
@iareintelligent how is this going? I would imagine we can close this?

**Comment by mikhaelbendavid** [comment]
@iareintelligent has this issue been resolved?

**Comment by iareintelligent** [comment]
Still working this.  There is a LOT of refactoring required.

**Comment by mikhael28** [comment]
@iareintelligent a quick update on things - @Vegitarius and I have worked on implementing the AWS Amplify withAuthenticator components into the web and native version of #thehub and have removed the front-end components you were working on!

We are able to modify the auth components, so we can theoretically add these back later - though to be honest, if you DO find the time to contribute some code, there might be something more interesting for you to contribute towards :)
