### ISSUE TITLE
Knowledge Base Resource Queue

### ISSUE THREAD

**Issue by mikhael28** [fsapprenticeship/fsa-hub#33]
2/4/2019 Update:
- Sanity API needs to be written to deploy new resource to prod dataset
- Hiding Resource-Approval Route in NavBar
        Subtask=> Add Amplify Auth into NavBar as well
- Adding Loading Animation during Resource Load

We want a way for FSA members to contribute to the knowledge base, however we want to make sure that only approved content comes through. 

This will require:
a) A dual-permissioned API for anyone who is a member of the FSA User-pool to submit a piece of content that includes:
- Name of resource entry
- Schema type that the entry falls into
- Description of resource
- URL
- Name of Website/Author who created the resource
- Approved (boolean value, default false)

b) Another view layer for admin permissioned users to 'approve' the proposed content
c) Once approved, the API will programatically submitting the piece of content to the production dataset programatically through the Sanity.io API.

Contributor1 will own the serverless Node API, and provisioning the DynamoDB table. She will write the serverless functions to submit the content, to approve the content, to query a list of all unnaproved content, and to pull a specific piece of content. 

Contributor2 will own the React components/forms to submit the content, and to approve the content/get it to display so the admin can review it before approving/denying. 

@mikhaelbendavid will create a separate user group for the admin users, special permissions. I will write Sanity API to programatically submit the content to the production dataset.

**Comment by mikhaelbendavid** [comment]
Estimates: Mikhael an hour to create the user pool. 
Submit Sanity API - 4 hours.
David Estimate Expo - 20 hours. 
Khayti - 12 hours to provision table, write functions and test with mock objects
5 hours to integrate into front end
Brian - 10 hour to create the forms. And writing the handle submits. 
5 hours to work together with Khayti.

**Comment by mikhael28** [comment]
This sprint did not quite work out - @bmhan319 had to go to Florida, and @khyati0212 couldn't put any time into it that week.

**Comment by mikhael28** [comment]
Vincent, RJ

**Comment by mikhael28** [comment]
@Vegitarius can you please add your estimate in number of hours for the work you need to accomplish this sprint?
@RJGrunau ditto

**Comment by Vegitarius** [comment]
Yeah same I'm not good at estimating but 4 hours sounds good for me.

**Comment by mikhael28** [comment]
@Vegitarius - took a few hours to onboard onto the code-base, and took right around 4 hours for the form components.

**Comment by mikhael28** [comment]
This is almost complete - I now need to write the Sanity API, we need to hide the Add Resource / Review resource buttons behind a 'AppliedRoute' (I don't think the hanging + sign is the best way to handle that functionality, especially since if someone isn't logged in - they won't be able to successfully send the request), update the forms a bit and we should be good! Tagging @Vegitarius here

**Comment by mikhael28** [comment]
Ryoku and I put an hour into this, this morning. @Vegitarius 's updateResource function works like a charm on the new resources api we put together with Amplify, I've written out most of the sanity query to programmatically add resources - now I need to add the authorization tokens, a few things, and test them tomorrow evening.

**Comment by mikhael28** [comment]
At looooong last, this ticket is closed :)
