### ISSUE TITLE
RN Expo Boostrap

### ISSUE THREAD

**Issue by mikhael28** [fsapprenticeship/fsa-hub#36]
Commit the starting base layer for the FSA Hub.

Navigation - Home, Chat, Knowledge, Profile

**Comment by mikhaelbendavid** [comment]
@davidmfry can you send a pull-request with the bootstrapped Expo application? We will plan to do  sprint planning meeting soon, perhaps on Tuesday after stand-up?

**Comment by mikhael28** [comment]
#34 was submitted and merged!
