### ISSUE TITLE
Additional Design Work Neccessary

### ISSUE THREAD

**Issue by nicholaswbowen** [fsapprenticeship/fsa-hub#38]
It seems like there's a general vision, but that there's a lot of working backwards from the tools, instead of the other way around (design first). I have a few questions for the team.

- Do you have a list of use-cases for your users?
- Do you have a defined MVP for what you want version 0.0.1 to look like?
- Do the tools you've picked fit the use cases you're trying to fulfill?

I ask these kinds of questions because trying to fit your design into your tools is how you end up with over-engineered solutions. I look forward to seeing what the end product becomes! Please mention me on your PRs if you want any additional insight.

Best,

-nick

**Comment by mikhael28** [comment]
@nicholaswbowen I've answered some of these questions through some 'Roadmap' tickets, going to go ahead and close this ticket :)
