### ISSUE TITLE
React Native - User Profile & Directory

### ISSUE THREAD

**Issue by andegwa1** [fsapprenticeship/fsa-hub#51]
Creating a user profile with a picture, location, bio, link to GitHub, and badge.

**Comment by mikhael28** [comment]
I've optimized the Profile screen a bit, though we still need the following data to pull from:
- First/Last, Community/TechnicalRank from Dynamo
- Uploading a photo to s3
- Uploading a resume/job history to s3/portfolio section.
- Badges component to visualize the 3 most 'prestigious' badges? Or, it could be the bottom and it keeps going down.

**Comment by andegwa1** [comment]
Next steps: 
- Set up profile picture upload to an S3 bucket

**Comment by mikhael28** [comment]
Decided to pull a user's avatar from their GitHub profile, minimize the data footprint FSA is accumulating. We want to be mindful of how much user data we collection, and to keep it to a minimum.

Additionally, this user API has now been built out and deployed using MongoDB. yay!
