### ISSUE TITLE
Messaging Front-End

### ISSUE THREAD

**Issue by mikhael28** [fsapprenticeship/fsa-hub#54]
Core Components:
- Find and pick a attractive messaging component library to integrate into the 1v1 messaging (DM)
- Design a static Direct Messaging screen
- Design a list view of potential, recent chats
- A view of the public messaging channel, real-time implementation.

**Comment by kp646576** [comment]
Initial estimate: 5 hours

**Comment by mikhael28** [comment]
@kp646576 the PR that you submitted satisfied all of these requirements, except perhaps for the last public view of the messaging channel. Closing this, opening another ticket to discuss the back-end integration.
