### ISSUE TITLE
Auth Registration Component/Testing

### ISSUE THREAD

**Issue by mikhael28** [fsapprenticeship/fsa-hub#61]
Make sure AWS Amplify works for registration/login, and that we can create an account/pull it for the profile.

**Comment by AspenJames** [comment]
@mikhael28 Is Auth completely set up in Web and Native?
@iareintelligent - you're going to work on testing React Web Authentication, right?
I'm happy to help out and/or take on the Native testing

**Comment by mikhael28** [comment]
@AspenJames auth is complete set-up and working in Native (with room for improvement, migration to Redux if we want), not quite sure what the status on Web is (but I removed the links from the nav until its finalized)

From what I understand, the /fancylogin route complete works - right @iareintelligent ?

**Comment by iareintelligent** [comment]
I'll be a normal programmer again very soon guys! Just been taking a hiatus
from screens since l've been nonstop visiting with friends/family.

**Comment by mikhael28** [comment]
AWS Amplify components remove the need for testing, as its a full, batteries-included solution!
