### ISSUE TITLE
GitHub API Integration

### ISSUE THREAD

**Issue by mikhael28** [fsapprenticeship/fsa-hub#62]
For an upcoming feature in the Community Tier, we want to offer basic Git integration to show:
- Tagged issues
- Notifications

For this ticket, please do some research on whether these two things are possible, and what other valuable items the GitHub API could conceivably offer to our student users.

**Comment by AspenJames** [comment]
Documentation for Issues: https://developer.github.com/v3/issues/

The docs are extremely detailed, and really the only resource you'll need to accomplish this!

**Comment by mikhael28** [comment]
@AspenJames that is perfect, thank you!

**Comment by mikhael28** [comment]
Closing this issue due to lack of specificity from the creator (myself). We will be integrating the Github API more as we add functionality for each of the projects that FSA members build, but that will come later.
